version: 2

jobs:
  build_test_deploy:
    docker:
      - image: circleci/node:10.7.0
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Melbourne"
    steps:
      - checkout
      - run: sudo npm update -g
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "89:58:dc:59:20:ad:6e:0a:01:3b:63:e9:f9:3a:fa:44"
      - run: ./deploy.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_test_deploy
